name: Push Docker Image to Docker Hub
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: cshyun/nodejs-ci
          tags: |
            # Tag with "latest" on the master branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            # 3. 브랜치 이름을 태그로 사용 (예: master, dev 등)
            type=ref,event=branch
            # Tag with semver for Git Tags (e.g., v1.0.0)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
